CREATE TABLE `database_tables`.`department` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(50) NOT NULL,
  `location` VARCHAR(200) NULL,
  `manager_id` INT NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `manager_email` VARCHAR(45) NOT NULL,
  `floor` INT NULL,
  `established_date` DATE NULL,
  `description` TEXT NULL,
  `created_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_by` INT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE INDEX `department_id_UNIQUE` (`department_id` ASC) VISIBLE,
  UNIQUE INDEX `department_name_UNIQUE` (`department_name` ASC) VISIBLE,
  UNIQUE INDEX `manager_id_UNIQUE` (`manager_id` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `manager_email_UNIQUE` (`manager_email` ASC) VISIBLE);
