CREATE TABLE `database_tables`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(10) NOT NULL,
  `age` INT NULL,
  `address` VARCHAR(200) NULL,
  `gender` VARCHAR(6) NULL,
  `profession` VARCHAR(30) NULL,
  `callification` VARCHAR(150) NOT NULL,
  `experience` INT NOT NULL,
  `created_by` INT NULL,
  `created_at` DATETIME NULL,
  `updated_by` INT NULL,
  `updated_at` DATETIME NULL,
  UNIQUE INDEX `staff_id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
