package com.mkpits.exceptionhandling;

public class DefaultHandling {
    // Exception Handling - run time error
	// two type of error - 1)Run time , 2)Compile time
	// Compile time error - the error generated by the compiler(syntactical problems)
	// Run time error - when we compile the program some error are occur that error is nothing but Exception/runtime error 
	public static void main(String[] args) {
		// TODO Auto-generated method stub
         int arr[] = new int[5];
        // System.out.println(arr[6]); // arrayindexoutofbond exception
         int x = 15,y=0;
         System.out.println(x/y);
	}

}
